//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImg
    {
        public int ImageId { get; set; }
        public int ProductId { get; set; }
        public int UrlId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Url Url { get; set; }
    }
}
