//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sepet()
        {
            this.Musteri = new HashSet<Musteri>();
        }
    
        public int sepetNo { get; set; }
        public int musteriNo { get; set; }
        public int siparisNo { get; set; }
        public string urunKodu { get; set; }
        public int urunAdedi { get; set; }
    
        public virtual Fatura Fatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteri> Musteri { get; set; }
        public virtual Musteri Musteri1 { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
