//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.Sepet = new HashSet<Sepet>();
            this.UrunResmi = new HashSet<UrunResmi>();
        }
    
        public int urunID { get; set; }
        public string urunKodu { get; set; }
        public string adi { get; set; }
        public string aciklama { get; set; }
        public double fiyat { get; set; }
        public int stokMiktari { get; set; }
        public int kategoriID { get; set; }
        public int cinsID { get; set; }
        public int cinsiyetID { get; set; }
        public int renkID { get; set; }
    
        public virtual Cins Cins { get; set; }
        public virtual Cinsiyet Cinsiyet { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Renk Renk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunResmi> UrunResmi { get; set; }
    }
}
