//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunResmi
    {
        public int resimID { get; set; }
        public int urunID { get; set; }
        public int urlID { get; set; }
    
        public virtual Url Url { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
